//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("cinemaModel", "fk_cinema_seat_cinema1", "cinema", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(CinemaCustomControlLibrary.cinema), "cinema_seat", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(CinemaCustomControlLibrary.cinema_seat), true)]

#endregion

namespace CinemaCustomControlLibrary
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class cinemaEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new cinemaEntities object using the connection string found in the 'cinemaEntities' section of the application configuration file.
        /// </summary>
        public cinemaEntities() : base("name=cinemaEntities", "cinemaEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new cinemaEntities object.
        /// </summary>
        public cinemaEntities(string connectionString) : base(connectionString, "cinemaEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new cinemaEntities object.
        /// </summary>
        public cinemaEntities(EntityConnection connection) : base(connection, "cinemaEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<cinema> cinemas
        {
            get
            {
                if ((_cinemas == null))
                {
                    _cinemas = base.CreateObjectSet<cinema>("cinemas");
                }
                return _cinemas;
            }
        }
        private ObjectSet<cinema> _cinemas;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<cinema_seat> cinema_seat
        {
            get
            {
                if ((_cinema_seat == null))
                {
                    _cinema_seat = base.CreateObjectSet<cinema_seat>("cinema_seat");
                }
                return _cinema_seat;
            }
        }
        private ObjectSet<cinema_seat> _cinema_seat;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the cinemas EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTocinemas(cinema cinema)
        {
            base.AddObject("cinemas", cinema);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the cinema_seat EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTocinema_seat(cinema_seat cinema_seat)
        {
            base.AddObject("cinema_seat", cinema_seat);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="cinemaModel", Name="cinema")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class cinema : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new cinema object.
        /// </summary>
        /// <param name="id">Initial value of the id property.</param>
        /// <param name="name">Initial value of the name property.</param>
        /// <param name="sound_id">Initial value of the sound_id property.</param>
        /// <param name="in_order">Initial value of the in_order property.</param>
        public static cinema Createcinema(global::System.Int32 id, global::System.String name, global::System.Int32 sound_id, global::System.Int32 in_order)
        {
            cinema cinema = new cinema();
            cinema.id = id;
            cinema.name = name;
            cinema.sound_id = sound_id;
            cinema.in_order = in_order;
            return cinema;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int32 _id;
        partial void OnidChanging(global::System.Int32 value);
        partial void OnidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String name
        {
            get
            {
                return _name;
            }
            set
            {
                OnnameChanging(value);
                ReportPropertyChanging("name");
                _name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("name");
                OnnameChanged();
            }
        }
        private global::System.String _name;
        partial void OnnameChanging(global::System.String value);
        partial void OnnameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 sound_id
        {
            get
            {
                return _sound_id;
            }
            set
            {
                Onsound_idChanging(value);
                ReportPropertyChanging("sound_id");
                _sound_id = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("sound_id");
                Onsound_idChanged();
            }
        }
        private global::System.Int32 _sound_id;
        partial void Onsound_idChanging(global::System.Int32 value);
        partial void Onsound_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> capacity
        {
            get
            {
                return _capacity;
            }
            set
            {
                OncapacityChanging(value);
                ReportPropertyChanging("capacity");
                _capacity = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("capacity");
                OncapacityChanged();
            }
        }
        private Nullable<global::System.Int32> _capacity;
        partial void OncapacityChanging(Nullable<global::System.Int32> value);
        partial void OncapacityChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 in_order
        {
            get
            {
                return _in_order;
            }
            set
            {
                Onin_orderChanging(value);
                ReportPropertyChanging("in_order");
                _in_order = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("in_order");
                Onin_orderChanged();
            }
        }
        private global::System.Int32 _in_order;
        partial void Onin_orderChanging(global::System.Int32 value);
        partial void Onin_orderChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("cinemaModel", "fk_cinema_seat_cinema1", "cinema_seat")]
        public EntityCollection<cinema_seat> cinema_seat
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<cinema_seat>("cinemaModel.fk_cinema_seat_cinema1", "cinema_seat");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<cinema_seat>("cinemaModel.fk_cinema_seat_cinema1", "cinema_seat", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="cinemaModel", Name="cinema_seat")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class cinema_seat : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new cinema_seat object.
        /// </summary>
        /// <param name="id">Initial value of the id property.</param>
        /// <param name="cinema_id">Initial value of the cinema_id property.</param>
        public static cinema_seat Createcinema_seat(global::System.Int32 id, global::System.Int32 cinema_id)
        {
            cinema_seat cinema_seat = new cinema_seat();
            cinema_seat.id = id;
            cinema_seat.cinema_id = cinema_id;
            return cinema_seat;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int32 _id;
        partial void OnidChanging(global::System.Int32 value);
        partial void OnidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 cinema_id
        {
            get
            {
                return _cinema_id;
            }
            set
            {
                Oncinema_idChanging(value);
                ReportPropertyChanging("cinema_id");
                _cinema_id = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("cinema_id");
                Oncinema_idChanged();
            }
        }
        private global::System.Int32 _cinema_id;
        partial void Oncinema_idChanging(global::System.Int32 value);
        partial void Oncinema_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> x1
        {
            get
            {
                return _x1;
            }
            set
            {
                Onx1Changing(value);
                ReportPropertyChanging("x1");
                _x1 = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("x1");
                Onx1Changed();
            }
        }
        private Nullable<global::System.Int32> _x1;
        partial void Onx1Changing(Nullable<global::System.Int32> value);
        partial void Onx1Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> y1
        {
            get
            {
                return _y1;
            }
            set
            {
                Ony1Changing(value);
                ReportPropertyChanging("y1");
                _y1 = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("y1");
                Ony1Changed();
            }
        }
        private Nullable<global::System.Int32> _y1;
        partial void Ony1Changing(Nullable<global::System.Int32> value);
        partial void Ony1Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> x2
        {
            get
            {
                return _x2;
            }
            set
            {
                Onx2Changing(value);
                ReportPropertyChanging("x2");
                _x2 = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("x2");
                Onx2Changed();
            }
        }
        private Nullable<global::System.Int32> _x2;
        partial void Onx2Changing(Nullable<global::System.Int32> value);
        partial void Onx2Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> y2
        {
            get
            {
                return _y2;
            }
            set
            {
                Ony2Changing(value);
                ReportPropertyChanging("y2");
                _y2 = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("y2");
                Ony2Changed();
            }
        }
        private Nullable<global::System.Int32> _y2;
        partial void Ony2Changing(Nullable<global::System.Int32> value);
        partial void Ony2Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> origin_x
        {
            get
            {
                return _origin_x;
            }
            set
            {
                Onorigin_xChanging(value);
                ReportPropertyChanging("origin_x");
                _origin_x = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("origin_x");
                Onorigin_xChanged();
            }
        }
        private Nullable<global::System.Int32> _origin_x;
        partial void Onorigin_xChanging(Nullable<global::System.Int32> value);
        partial void Onorigin_xChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> origin_y
        {
            get
            {
                return _origin_y;
            }
            set
            {
                Onorigin_yChanging(value);
                ReportPropertyChanging("origin_y");
                _origin_y = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("origin_y");
                Onorigin_yChanged();
            }
        }
        private Nullable<global::System.Int32> _origin_y;
        partial void Onorigin_yChanging(Nullable<global::System.Int32> value);
        partial void Onorigin_yChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String row_name
        {
            get
            {
                return _row_name;
            }
            set
            {
                Onrow_nameChanging(value);
                ReportPropertyChanging("row_name");
                _row_name = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("row_name");
                Onrow_nameChanged();
            }
        }
        private global::System.String _row_name;
        partial void Onrow_nameChanging(global::System.String value);
        partial void Onrow_nameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String col_name
        {
            get
            {
                return _col_name;
            }
            set
            {
                Oncol_nameChanging(value);
                ReportPropertyChanging("col_name");
                _col_name = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("col_name");
                Oncol_nameChanged();
            }
        }
        private global::System.String _col_name;
        partial void Oncol_nameChanging(global::System.String value);
        partial void Oncol_nameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> object_type
        {
            get
            {
                return _object_type;
            }
            set
            {
                Onobject_typeChanging(value);
                ReportPropertyChanging("object_type");
                _object_type = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("object_type");
                Onobject_typeChanged();
            }
        }
        private Nullable<global::System.Int32> _object_type;
        partial void Onobject_typeChanging(Nullable<global::System.Int32> value);
        partial void Onobject_typeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.SByte> is_handicapped
        {
            get
            {
                return _is_handicapped;
            }
            set
            {
                Onis_handicappedChanging(value);
                ReportPropertyChanging("is_handicapped");
                _is_handicapped = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("is_handicapped");
                Onis_handicappedChanged();
            }
        }
        private Nullable<global::System.SByte> _is_handicapped;
        partial void Onis_handicappedChanging(Nullable<global::System.SByte> value);
        partial void Onis_handicappedChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("cinemaModel", "fk_cinema_seat_cinema1", "cinema")]
        public cinema cinema
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<cinema>("cinemaModel.fk_cinema_seat_cinema1", "cinema").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<cinema>("cinemaModel.fk_cinema_seat_cinema1", "cinema").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<cinema> cinemaReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<cinema>("cinemaModel.fk_cinema_seat_cinema1", "cinema");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<cinema>("cinemaModel.fk_cinema_seat_cinema1", "cinema", value);
                }
            }
        }

        #endregion

    }

    #endregion

    
}
